name: Release
on:
  push:
    tags:
    - 0.*

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    # - name: Import GPG key
      # id: import_gpg
      # uses: crazy-max/ghaction-import-gpg@v5
      # with:
        # gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        # passphrase: ${{ secrets.GPG_PASSPHRASE }}

    # - name: List Keys
      # run: gpg -K

    - name: Build
      run: |
        cargo build --release

    # - name: Code Sign
      # uses: dlemstra/code-sign-action@v1
      # with:
        # certificate: '${{ secrets.CODE_SIGN_CERTIFICATE }}'
        # password: '${{ secrets.CODE_SIGN_PASSWORD }}'
        # recursive: false
        # files: |
          # target/release/deucalion.dll

    # - name: SHA256Sum and GPG Sign
      # run: |
        # sha256sum target/release/deucalion.dll > deucalion.sha256sum
        # gpg --output deucalion.sha256sum.asc --clearsign deucalion.sha256sum
        # cat deucalion.sha256sum.asc

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: deucalion
        path: |
          target/release/deucalion.dll

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Deucalion ${{ github.ref_name }}
        body: "# CHANGELOG"
        draft: true
        files: |
          deucalion/target/release/deucalion.dll